language: python

python:
  - 2.6
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.4

matrix:
  exclude:
    - env: DJANGO_VERSION=1.4.8
      python: 3.3


install:
  - pip install -r requirements_test.txt
  - pip install django==$DJANGO_VERSION
  - python setup.py develop

script: coverage run example_project/manage.py test photologue

after_success:
  - coveralls

