language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1

install:
  - pip install -r requirements_test.txt
  - pip install django==$DJANGO_VERSION
  - python setup.py develop

script: coverage run manage.py test photologue

after_success:
  - coveralls
