language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1

matrix:
  exclude:
    - env: DJANGO_VERSION=1.4.5
      python: 3.3


install:
  - pip install -e requirements_test.txt
  - pip install django==$DJANGO_VERSION
  - python setup.py develop

script: cd example_project; coverage run --source='photologue' manage.py test photologue

after_success:
  - cd example_project; coveralls
