language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1

install:
  - pip install django==$DJANGO_VERSION
  - python setup.py develop

script: cd example_project; python manage.py test photologue

